name: Cut a release

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Commit and push
        run: |-
          echo "$(date -u)" > file.txt
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Latest data: $(date -u)"
          git push
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "file.txt"
          bodyFile: "README.md"
          commit: main