name: Cut a release

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Commit and push
        run: |-
          echo "$(date -u)" > file.txt
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Latest data: $(date -u)"

          git fetch --tags
          # Get the latest tag
          latestTag="$(git describe --tags `git rev-list --tags --max-count=1`)"
          # increment it by 0.0.1
          newTag="$(echo $latestTag | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"

          echo "Bumping version from $latestTag to $newTag"
          git tag $newTag
          git push origin $newTag
          git push

          echo "NEW_TAG=$newTag" >> $GITHUB_ENV

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "file.txt"
          bodyFile: "README.md"
          tag: ${{env.NEW_TAG}}